"""MIT. Generate the missing suite READMEs from each suite's own recorded metadata.

The evidence sweep (`tests/test_evidence_integrity.py`) found that most published suites have
no README, including many that the board ledger links to. This generator writes a factual,
terse page per suite from what the suite itself records - the manifest, the board results and
the files on disk. It never invents prose:

* if a suite already has a `README.md` **without** the generated marker, it is left untouched
  (hand-written pages win, always);
* a generated page carries a marker line, a table of the models, the board summary, the file
  inventory and the reproduce commands, and ends with a "Notes" section for a human to extend.

    PYTHONPATH=src python research/build_suite_readmes.py            # write missing pages
    PYTHONPATH=src python research/build_suite_readmes.py --check    # verify they are current
"""
from pathlib import Path
import argparse
import json
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from open_rknpu.model import decode as decode_model          # noqa: E402
from open_rknpu.sequence import decode_sequence             # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RESEARCH = ROOT / "research"
MARKER = "<!-- generated by research/build_suite_readmes.py -->"
LEDGER = RESEARCH / "COVERAGE_EXPANSION_RESULTS.md"


def ledger_suites():
    return sorted(set(re.findall(r"\]\(([a-z0-9_]+_suite)/\)", LEDGER.read_text())))


def decode_container(suite, index):
    """Decode a retained container, or return None when it is absent/unreadable."""
    path = suite / ("model%03d.bin" % int(index))
    if not path.is_file():
        return None
    data = path.read_bytes()
    try:
        return decode_sequence(data) if data[:8] == b"ORNPUSEQ" else decode_model(data)
    except ValueError:
        return None


def summarize(entry, info):
    """A compact description taken from the manifest, else from the decoded container."""
    pieces = []
    for key in ("label", "profile", "elementwise_profile", "join_kinds", "join", "pool",
                "fused_activation", "ops"):
        value = entry.get(key)
        if value:
            pieces.append("%s=%s" % (key, value if not isinstance(value, list) else "->".join(map(str, value))))
    if not pieces and info:
        pieces.append("profile=%s" % info["profile"] if info.get("profile") is not None
                      else "container=v%s" % info.get("format_version"))
        operators = info.get("operators")
        if operators:
            pieces.append("ops=%s" % "->".join(map(str, operators)))
        kernel = info.get("kernel_size")
        if kernel:
            pieces.append("K%s" % kernel)
        if info.get("relu"):
            pieces.append("relu")
    return ", ".join(pieces) or "-"


def band(info, which):
    if not info:
        return "-"
    scale = info.get("%s_scale" % which)
    zero = info.get("%s_zero_point" % which)
    if scale is None:
        return "-"
    return "%.6g/%d" % (scale, zero if zero is not None else 0)


def shape_text(entry, *keys):
    for key in keys:
        value = entry.get(key)
        if isinstance(value, list) and value:
            return "x".join(str(item) for item in value)
    return "-"


def board_totals(suite):
    passed = failed = 0
    seen = {}
    for path in sorted(suite.glob("board_results_*.json")):
        for entry in json.loads(path.read_text()):
            key = str(entry.get("model"))
            previous = seen.get(key)
            if previous is None or (entry.get("passed") and not previous):
                seen[key] = bool(entry.get("passed"))
    for value in seen.values():
        passed += 1 if value else 0
        failed += 0 if value else 1
    return passed, failed


def summary_line(suite):
    for path in sorted(suite.glob("board_summary.txt")):
        return path.read_text().strip()
    return None


def render(suite):
    manifest_path = suite / "manifest.json"
    manifest = json.loads(manifest_path.read_text()) if manifest_path.is_file() else []
    entries = [entry for entry in manifest if isinstance(entry, dict)] if isinstance(manifest, list) else []
    generator = RESEARCH / f"build_{suite.name.replace('_suite', '')}.py"
    passed, failed = board_totals(suite)
    outputs = sorted(suite.glob("expected*.i8"))
    containers = sorted(suite.glob("model*.bin"))
    inputs = sorted(suite.glob("input*.u8"))
    summary = summary_line(suite)
    has_board = bool(list(suite.glob("board_results_*.json")))
    evidence = ("board results: **%d passing**, %d failing" % (passed, failed) if has_board
                else "no machine-readable `board_results_*.json` in this suite; its recorded "
                     "run lives in the board ledger and/or the notes below")
    lines = [
        "# `%s`" % suite.name,
        "",
        MARKER,
        "",
        "Evidence suite: %d container(s), %d reference output(s), %d input file(s); %s."
        % (len(containers), len(outputs), len(inputs), evidence),
        "",
    ]
    if entries:
        lines += ["## Models", "",
                  "| model | profile / ops | input (band) | output (band) | tasks | cases |",
                  "| --- | --- | --- | --- | --- | --- |"]
        for entry in entries:
            index = entry.get("index")
            if index is None:
                continue
            info = decode_container(suite, index)
            # The container is the authority on geometry; the manifest is the fallback
            # (its shape fields are HWC/CHW in some suites).
            input_shape = "x".join(str(v) for v in info["shape_nhwc"]) if info else \
                shape_text(entry, "input_shape", "shape_nhwc")
            output_shape = "x".join(str(v) for v in info["output_shape_nhwc"]) if info else \
                shape_text(entry, "output_shape", "output_shape_nhwc")
            tasks = info.get("task_count") if info else None
            lines.append("| %03d | %s | %s (%s) | %s (%s) | %s | %s |" % (
                int(index), summarize(entry, info), input_shape, band(info, "input"),
                output_shape, band(info, "output"), tasks if tasks is not None else "-",
                entry.get("cases", "-")))
        lines.append("")
    else:
        lines += ["The manifest for this suite is not a list of model entries; read it directly.",
                  ""]
    if summary:
        lines += ["## Board evidence", "", "```", summary, "```", ""]
    lines += ["## Files", "",
              "* containers: `modelNNN.bin` (%d)" % len(containers),
              "* reference outputs: `expectedNNN.i8` (%d)" % len(outputs),
              "* inputs: `inputNNN.u8` (%d)" % len(inputs),
              "* `manifest.json`, `board_results_*.json`, `board_summary.txt`", "",
              "## Reproduce", ""]
    if generator.is_file():
        lines.append("* regenerate the suite: `PYTHONPATH=src python research/%s`" % generator.name)
    lines += [
        "* run it on the board: `make board-suite SUITE=%s` (needs `$ADB` and the cross toolchain)" % suite.name,
        "* recompile without hardware: `PYTHONPATH=src python research/verify_suites.py`", "",
        "## Notes", "",
        "Add what this suite demonstrates, the bound it pins and any caveat here; this section is",
        "never regenerated once you edit the file (the marker only matters for untouched pages).",
        "",
    ]
    return "\n".join(lines)


def targets(only=None):
    for suite in sorted(path for path in RESEARCH.glob("*_suite") if path.is_dir()):
        if only and suite.name != only:
            continue
        readme = suite / "README.md"
        if readme.is_file() and MARKER not in readme.read_text(errors="ignore"):
            continue
        yield suite, readme


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify the generated pages are current")
    parser.add_argument("--only", default=None, help="one suite name")
    args = parser.parse_args()
    written = stale = 0
    for suite, readme in targets(args.only):
        content = render(suite)
        if args.check:
            if not readme.is_file() or readme.read_text() != content:
                print("stale:", suite.name)
                stale += 1
            continue
        readme.write_text(content)
        written += 1
    if args.check:
        print("checked generated suite pages; stale:", stale)
        raise SystemExit(1 if stale else 0)
    print("wrote", written, "suite README(s); ledger suites:", len(ledger_suites()))


if __name__ == "__main__":
    main()
